language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
before_install:
  - gem update --system
  - gem --version # make sure rubygems actually were updated
before_script:
  - "psql -U postgres -c 'create database tree_test;'"
script: bundle exec rake test
